import { CountryItem } from "./app";

export const LATAM_SPAIN_USA_CODES = new Set([
  "PE", "MX", "ES", "US", "CO", "AR", "CL", "EC", "BO", "VE",
  "BR", "UY", "PY", "CR", "GT", "PA", "DO", "SV", "HN", "NI", "CU", "PR"
]);

export const ALL_COUNTRIES: CountryItem[] = [
  // --- AMÉRICA LATINA, ESPAÑA Y EE.UU. (PRIORITARIOS) ---
  { iso: "PE", code: "+51", name: "Perú", flag: "🇵🇪" },
  { iso: "MX", code: "+52", name: "México", flag: "🇲🇽" },
  { iso: "ES", code: "+34", name: "España", flag: "🇪🇸" },
  { iso: "US", code: "+1", name: "Estados Unidos", flag: "🇺🇸" },
  { iso: "CO", code: "+57", name: "Colombia", flag: "🇨🇴" },
  { iso: "AR", code: "+54", name: "Argentina", flag: "🇦🇷" },
  { iso: "CL", code: "+56", name: "Chile", flag: "🇨🇱" },
  { iso: "EC", code: "+593", name: "Ecuador", flag: "🇪🇨" },
  { iso: "BO", code: "+591", name: "Bolivia", flag: "🇧🇴" },
  { iso: "VE", code: "+58", name: "Venezuela", flag: "🇻🇪" },
  { iso: "BR", code: "+55", name: "Brasil", flag: "🇧🇷" },
  { iso: "UY", code: "+598", name: "Uruguay", flag: "🇺🇾" },
  { iso: "PY", code: "+595", name: "Paraguay", flag: "🇵🇾" },
  { iso: "CR", code: "+506", name: "Costa Rica", flag: "🇨🇷" },
  { iso: "GT", code: "+502", name: "Guatemala", flag: "🇬🇹" },
  { iso: "PA", code: "+507", name: "Panamá", flag: "🇵🇦" },
  { iso: "DO", code: "+1", name: "República Dominicana", flag: "🇩🇴" },
  { iso: "SV", code: "+503", name: "El Salvador", flag: "🇸🇻" },
  { iso: "HN", code: "+504", name: "Honduras", flag: "🇭🇳" },
  { iso: "NI", code: "+505", name: "Nicaragua", flag: "🇳🇮" },
  { iso: "CU", code: "+53", name: "Cuba", flag: "🇨🇺" },
  { iso: "PR", code: "+1", name: "Puerto Rico", flag: "🇵🇷" },

  // --- TODOS LOS DEMÁS PAÍSES DEL MUNDO (A - Z) ---
  { iso: "AF", code: "+93", name: "Afganistán", flag: "🇦🇫" },
  { iso: "AL", code: "+355", name: "Albania", flag: "🇦🇱" },
  { iso: "DE", code: "+49", name: "Alemania", flag: "🇩🇪" },
  { iso: "AD", code: "+376", name: "Andorra", flag: "🇦🇩" },
  { iso: "AO", code: "+244", name: "Angola", flag: "🇦🇴" },
  { iso: "AI", code: "+1264", name: "Anguila", flag: "🇦🇮" },
  { iso: "AG", code: "+1268", name: "Antigua y Barbuda", flag: "🇦🇬" },
  { iso: "SA", code: "+966", name: "Arabia Saudita", flag: "🇸🇦" },
  { iso: "DZ", code: "+213", name: "Argelia", flag: "🇩🇿" },
  { iso: "AM", code: "+374", name: "Armenia", flag: "🇦🇲" },
  { iso: "AW", code: "+297", name: "Aruba", flag: "🇦🇼" },
  { iso: "AU", code: "+61", name: "Australia", flag: "🇦🇺" },
  { iso: "AT", code: "+43", name: "Austria", flag: "🇦🇹" },
  { iso: "AZ", code: "+994", name: "Azerbaiyán", flag: "🇦🇿" },
  { iso: "BS", code: "+1242", name: "Bahamas", flag: "🇧🇸" },
  { iso: "BD", code: "+880", name: "Bangladesh", flag: "🇧🇩" },
  { iso: "BB", code: "+1246", name: "Barbados", flag: "🇧🇧" },
  { iso: "BH", code: "+973", name: "Bahréin", flag: "🇧🇭" },
  { iso: "BE", code: "+32", name: "Bélgica", flag: "🇧🇪" },
  { iso: "BZ", code: "+501", name: "Belice", flag: "🇧🇿" },
  { iso: "BJ", code: "+229", name: "Benín", flag: "🇧🇯" },
  { iso: "BM", code: "+1441", name: "Bermudas", flag: "🇧🇲" },
  { iso: "BY", code: "+375", name: "Bielorrusia", flag: "🇧🇾" },
  { iso: "MM", code: "+95", name: "Birmania (Myanmar)", flag: "🇲🇲" },
  { iso: "BA", code: "+387", name: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { iso: "BW", code: "+267", name: "Botsuana", flag: "🇧🇼" },
  { iso: "BN", code: "+673", name: "Brunéi", flag: "🇧🇳" },
  { iso: "BG", code: "+359", name: "Bulgaria", flag: "🇧🇬" },
  { iso: "BF", code: "+226", name: "Burkina Faso", flag: "🇧🇫" },
  { iso: "BI", code: "+257", name: "Burundi", flag: "🇧🇮" },
  { iso: "BT", code: "+975", name: "Bután", flag: "🇧🇹" },
  { iso: "CV", code: "+238", name: "Cabo Verde", flag: "🇨🇻" },
  { iso: "KH", code: "+855", name: "Camboya", flag: "🇰🇭" },
  { iso: "CM", code: "+237", name: "Camerún", flag: "🇨🇲" },
  { iso: "CA", code: "+1", name: "Canadá", flag: "🇨🇦" },
  { iso: "QA", code: "+974", name: "Catar", flag: "🇶🇦" },
  { iso: "TD", code: "+235", name: "Chad", flag: "🇹🇩" },
  { iso: "CZ", code: "+420", name: "Chequia (Rep. Checa)", flag: "🇨🇿" },
  { iso: "CN", code: "+86", name: "China", flag: "🇨🇳" },
  { iso: "CY", code: "+357", name: "Chipre", flag: "🇨🇾" },
  { iso: "KM", code: "+269", name: "Comoras", flag: "🇰🇲" },
  { iso: "CG", code: "+242", name: "Congo", flag: "🇨🇬" },
  { iso: "CD", code: "+243", name: "Congo (Rep. Dem.)", flag: "🇨🇩" },
  { iso: "KP", code: "+850", name: "Corea del Norte", flag: "🇰🇵" },
  { iso: "KR", code: "+82", name: "Corea del Sur", flag: "🇰🇷" },
  { iso: "CI", code: "+225", name: "Costa de Marfil", flag: "🇨🇮" },
  { iso: "HR", code: "+385", name: "Croacia", flag: "🇭🇷" },
  { iso: "CW", code: "+599", name: "Curazao", flag: "🇨🇼" },
  { iso: "DK", code: "+45", name: "Dinamarca", flag: "🇩🇰" },
  { iso: "DM", code: "+1767", name: "Dominica", flag: "🇩🇲" },
  { iso: "EG", code: "+20", name: "Egipto", flag: "🇪🇬" },
  { iso: "AE", code: "+971", name: "Emiratos Árabes Unidos", flag: "🇦🇪" },
  { iso: "ER", code: "+291", name: "Eritrea", flag: "🇪🇷" },
  { iso: "SK", code: "+421", name: "Eslovaquia", flag: "🇸🇰" },
  { iso: "SI", code: "+386", name: "Eslovenia", flag: "🇸🇮" },
  { iso: "EE", code: "+372", name: "Estonia", flag: "🇪🇪" },
  { iso: "SZ", code: "+268", name: "Esuatini (Suazilandia)", flag: "🇸🇿" },
  { iso: "ET", code: "+251", name: "Etiopía", flag: "🇪🇹" },
  { iso: "PH", code: "+63", name: "Filipinas", flag: "🇵🇭" },
  { iso: "FI", code: "+358", name: "Finlandia", flag: "🇫🇮" },
  { iso: "FJ", code: "+679", name: "Fiyi", flag: "🇫🇯" },
  { iso: "FR", code: "+33", name: "Francia", flag: "🇫🇷" },
  { iso: "GA", code: "+241", name: "Gabón", flag: "🇬🇦" },
  { iso: "GM", code: "+220", name: "Gambia", flag: "🇬🇲" },
  { iso: "GE", code: "+995", name: "Georgia", flag: "🇬🇪" },
  { iso: "GH", code: "+233", name: "Ghana", flag: "🇬🇭" },
  { iso: "GI", code: "+350", name: "Gibraltar", flag: "🇬🇮" },
  { iso: "GD", code: "+1473", name: "Granada", flag: "🇬🇩" },
  { iso: "GR", code: "+30", name: "Grecia", flag: "🇬🇷" },
  { iso: "GL", code: "+299", name: "Groenlandia", flag: "🇬🇱" },
  { iso: "GP", code: "+590", name: "Guadalupe", flag: "🇬🇵" },
  { iso: "GU", code: "+1671", name: "Guam", flag: "🇬🇺" },
  { iso: "GN", code: "+224", name: "Guinea", flag: "🇬🇳" },
  { iso: "GQ", code: "+240", name: "Guinea Ecuatorial", flag: "🇬🇶" },
  { iso: "GW", code: "+245", name: "Guinea-Bisáu", flag: "🇬🇼" },
  { iso: "GY", code: "+592", name: "Guyana", flag: "🇬🇾" },
  { iso: "HT", code: "+509", name: "Haití", flag: "🇭🇹" },
  { iso: "NL", code: "+31", name: "Holanda (Países Bajos)", flag: "🇳🇱" },
  { iso: "HU", code: "+36", name: "Hungría", flag: "🇭🇺" },
  { iso: "IN", code: "+91", name: "India", flag: "🇮🇳" },
  { iso: "ID", code: "+62", name: "Indonesia", flag: "🇮🇩" },
  { iso: "IQ", code: "+964", name: "Irak", flag: "🇮🇶" },
  { iso: "IR", code: "+98", name: "Irán", flag: "🇮🇷" },
  { iso: "IE", code: "+353", name: "Irlanda", flag: "🇮🇪" },
  { iso: "IS", code: "+354", name: "Islandia", flag: "🇮🇸" },
  { iso: "IL", code: "+972", name: "Israel", flag: "🇮🇱" },
  { iso: "IT", code: "+39", name: "Italia", flag: "🇮🇹" },
  { iso: "JM", code: "+1876", name: "Jamaica", flag: "🇯🇲" },
  { iso: "JP", code: "+81", name: "Japón", flag: "🇯🇵" },
  { iso: "JO", code: "+962", name: "Jordania", flag: "🇯🇴" },
  { iso: "KZ", code: "+7", name: "Kazajistán", flag: "🇰🇿" },
  { iso: "KE", code: "+254", name: "Kenia", flag: "🇰🇪" },
  { iso: "KG", code: "+996", name: "Kirguistán", flag: "🇰🇬" },
  { iso: "KW", code: "+965", name: "Kuwait", flag: "🇰🇼" },
  { iso: "LA", code: "+856", name: "Laos", flag: "🇱🇦" },
  { iso: "LS", code: "+266", name: "Lesoto", flag: "🇱🇸" },
  { iso: "LV", code: "+371", name: "Letonia", flag: "🇱🇻" },
  { iso: "LB", code: "+961", name: "Líbano", flag: "🇱🇧" },
  { iso: "LR", code: "+231", name: "Liberia", flag: "🇱🇷" },
  { iso: "LY", code: "+218", name: "Libia", flag: "🇱🇾" },
  { iso: "LI", code: "+423", name: "Liechtenstein", flag: "🇱🇮" },
  { iso: "LT", code: "+370", name: "Lituania", flag: "🇱🇹" },
  { iso: "LU", code: "+352", name: "Luxemburgo", flag: "🇱🇺" },
  { iso: "MK", code: "+389", name: "Macedonia del Norte", flag: "🇲🇰" },
  { iso: "MG", code: "+261", name: "Madagascar", flag: "🇲🇬" },
  { iso: "MY", code: "+60", name: "Malasia", flag: "🇲🇾" },
  { iso: "MW", code: "+265", name: "Malaui", flag: "🇲🇼" },
  { iso: "MV", code: "+960", name: "Maldivas", flag: "🇲🇻" },
  { iso: "ML", code: "+223", name: "Malí", flag: "🇲🇱" },
  { iso: "MT", code: "+356", name: "Malta", flag: "🇲🇹" },
  { iso: "MA", code: "+212", name: "Marruecos", flag: "🇲🇦" },
  { iso: "MU", code: "+230", name: "Mauricio", flag: "🇲🇺" },
  { iso: "MR", code: "+222", name: "Mauritania", flag: "🇲🇷" },
  { iso: "MD", code: "+373", name: "Moldavia", flag: "🇲🇩" },
  { iso: "MC", code: "+377", name: "Mónaco", flag: "🇲🇨" },
  { iso: "MN", code: "+976", name: "Mongolia", flag: "🇲🇳" },
  { iso: "ME", code: "+382", name: "Montenegro", flag: "🇲🇪" },
  { iso: "MZ", code: "+258", name: "Mozambique", flag: "🇲🇿" },
  { iso: "NA", code: "+264", name: "Namibia", flag: "🇳🇦" },
  { iso: "NP", code: "+977", name: "Nepal", flag: "🇳🇵" },
  { iso: "NE", code: "+227", name: "Níger", flag: "🇳🇪" },
  { iso: "NG", code: "+234", name: "Nigeria", flag: "🇳🇬" },
  { iso: "NO", code: "+47", name: "Noruega", flag: "🇳🇴" },
  { iso: "NZ", code: "+64", name: "Nueva Zelanda", flag: "🇳🇿" },
  { iso: "OM", code: "+968", name: "Omán", flag: "🇴🇲" },
  { iso: "PK", code: "+92", name: "Pakistán", flag: "🇵🇰" },
  { iso: "PS", code: "+970", name: "Palestina", flag: "🇵🇸" },
  { iso: "PG", code: "+675", name: "Papúa Nueva Guinea", flag: "🇵🇬" },
  { iso: "PL", code: "+48", name: "Polonia", flag: "🇵🇱" },
  { iso: "PT", code: "+351", name: "Portugal", flag: "🇵🇹" },
  { iso: "GB", code: "+44", name: "Reino Unido", flag: "🇬🇧" },
  { iso: "CF", code: "+236", name: "República Centroafricana", flag: "🇨🇫" },
  { iso: "RO", code: "+40", name: "Rumanía", flag: "🇷🇴" },
  { iso: "RU", code: "+7", name: "Rusia", flag: "🇷🇺" },
  { iso: "WS", code: "+685", name: "Samoa", flag: "🇼🇸" },
  { iso: "SM", code: "+378", name: "San Marino", flag: "🇸🇲" },
  { iso: "SN", code: "+221", name: "Senegal", flag: "🇸🇳" },
  { iso: "RS", code: "+381", name: "Serbia", flag: "🇷🇸" },
  { iso: "SG", code: "+65", name: "Singapur", flag: "🇸🇬" },
  { iso: "SY", code: "+963", name: "Siria", flag: "🇸🇾" },
  { iso: "SO", code: "+252", name: "Somalia", flag: "🇸🇴" },
  { iso: "LK", code: "+94", name: "Sri Lanka", flag: "🇱🇰" },
  { iso: "ZA", code: "+27", name: "Sudáfrica", flag: "🇿🇦" },
  { iso: "SD", code: "+249", name: "Sudán", flag: "🇸🇩" },
  { iso: "SE", code: "+46", name: "Suecia", flag: "🇸🇪" },
  { iso: "CH", code: "+41", name: "Suiza", flag: "🇨🇭" },
  { iso: "SR", code: "+597", name: "Surinam", flag: "🇸🇷" },
  { iso: "TH", code: "+66", name: "Tailandia", flag: "🇹🇭" },
  { iso: "TW", code: "+886", name: "Taiwán", flag: "🇹🇼" },
  { iso: "TZ", code: "+255", name: "Tanzania", flag: "🇹🇿" },
  { iso: "TJ", code: "+992", name: "Tayikistán", flag: "🇹🇯" },
  { iso: "TL", code: "+670", name: "Timor Oriental", flag: "🇹🇱" },
  { iso: "TG", code: "+228", name: "Togo", flag: "🇹🇬" },
  { iso: "TT", code: "+1868", name: "Trinidad y Tobago", flag: "🇹🇹" },
  { iso: "TN", code: "+216", name: "Túnez", flag: "🇹🇳" },
  { iso: "TM", code: "+993", name: "Turkmenistán", flag: "🇹🇲" },
  { iso: "TR", code: "+90", name: "Turquía", flag: "🇹🇷" },
  { iso: "UA", code: "+380", name: "Ucrania", flag: "🇺🇦" },
  { iso: "UG", code: "+256", name: "Uganda", flag: "🇺🇬" },
  { iso: "UZ", code: "+998", name: "Uzbekistán", flag: "🇺🇿" },
  { iso: "VA", code: "+39", name: "Vaticano", flag: "🇻🇦" },
  { iso: "VN", code: "+84", name: "Vietnam", flag: "🇻🇳" },
  { iso: "YE", code: "+967", name: "Yemen", flag: "🇾🇪" },
  { iso: "DJ", code: "+253", name: "Yibuti", flag: "🇩🇯" },
  { iso: "ZM", code: "+260", name: "Zambia", flag: "🇿🇲" },
  { iso: "ZW", code: "+263", name: "Zimbabue", flag: "🇿🇼" }
];
